# PostgreSQL. Versions 9.1 and up are supported.

# We use postgres in development cause it will give us less headaches when
# deploying

default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: petclinic_development

  username: rails
  password: password
  host: localhost
  port: 5432

  # Schema search path. The server defaults to $user,public
  #schema_search_path: myapp,sharedapp,public

  # Minimum log levels, in increasing order:
  #   debug5, debug4, debug3, debug2, debug1,
  #   log, notice, warning, error, fatal, and panic
  # Defaults to warning.
  #min_messages: notice

test:
  <<: *default
  database: petclinic_test

# We go with url as env variable when deploying
production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
